import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'es-MX' | 'en-US';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translations
const translations = {
  'es-MX': {
    // Header
    'header.title': 'Notinvent',
    'header.dashboard': 'Panel',
    'header.scan': 'Escanear',
    'header.configuration': 'Configuración',
    'header.history': 'Historial',
    'header.connected': 'Conectado',
    'header.disconnected': 'Desconectado',
    'header.demoMode': 'Modo Demo',
    'header.disconnect': 'Desconectar',
    'header.exitDemo': 'Salir del modo demo',
    
    // Theme
    'theme.light': 'Modo Claro',
    'theme.dark': 'Modo Oscuro',
    'theme.system': 'Seguir Sistema',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Crear Cuenta',
    'auth.logout': 'Cerrar Sesión',
    'auth.userSettings': 'Configuración de Usuario',
    'auth.confirmLogout': '¿Estás seguro de que quieres cerrar sesión?',
    'auth.welcome': 'Bienvenido',
    'auth.welcomeBack': 'Bienvenido de vuelta',
    'auth.accountCreated': 'Cuenta creada exitosamente',
    'auth.loginSuccess': 'Sesión iniciada correctamente',
    'auth.logoutSuccess': 'Sesión cerrada correctamente',
    'auth.invalidCredentials': 'Credenciales inválidas',
    'auth.emailRequired': 'El email es requerido',
    'auth.passwordRequired': 'La contraseña es requerida',
    'auth.nameRequired': 'El nombre es requerido',
    'auth.emailInvalid': 'Ingresa un email válido',
    'auth.passwordTooShort': 'La contraseña debe tener al menos 8 caracteres',
    'auth.passwordsNotMatch': 'Las contraseñas no coinciden',
    'auth.emailExists': 'Este email ya está registrado',
    'auth.userNotFound': 'Usuario no encontrado',
    'auth.networkError': 'Error de conexión. Verifica tu internet.',
    
    // Connection View
    'connection.title': 'Conectar a Notion',
    'connection.subtitle': 'Ingresa tus credenciales de integración de Notion para comenzar',
    'connection.demoButton': 'Explorar en Modo Demo',
    'connection.demoSubtitle': 'Prueba todas las funcionalidades sin configuración',
    'connection.orConnect': 'o conecta tu Notion',
    'connection.token': 'Token de Integración',
    'connection.tokenPlaceholder': 'secret_...',
    'connection.tokenRequired': 'El token de integración es requerido',
    'connection.databaseId': 'ID de Base de Datos',
    'connection.databaseIdPlaceholder': 'ID de la base de datos desde la URL de Notion',
    'connection.databaseIdRequired': 'El ID de la base de datos es requerido',
    'connection.workspaceName': 'Nombre del Workspace (Opcional)',
    'connection.workspaceNamePlaceholder': 'Mi Workspace de Empresa',
    'connection.connecting': 'Conectando...',
    'connection.connect': 'Conectar a Notion',
    'connection.setupInstructions': 'Instrucciones de Configuración:',
    'connection.step1': 'Crear una integración en notion.so/my-integrations',
    'connection.step2': 'Copiar el token de integración',
    'connection.step3': 'Compartir tu base de datos con la integración',
    'connection.step4': 'Copiar el ID de la base de datos desde la URL',
    
    // Dashboard
    'dashboard.title': 'Panel de Control',
    'dashboard.subtitle': 'Resumen de tu sistema de gestión de inventario',
    'dashboard.refresh': 'Actualizar',
    'dashboard.totalItems': 'Total de Artículos',
    'dashboard.available': 'Disponibles',
    'dashboard.recentScans': 'Escaneos Recientes',
    'dashboard.needsAttention': 'Requiere Atención',
    'dashboard.recentActivity': 'Actividad Reciente',
    'dashboard.noActivity': 'Sin actividad reciente',
    'dashboard.startScanning': 'Comienza a escanear para ver actividad aquí',
    'dashboard.scannedWith': 'Escaneado con',
    'dashboard.needsAttentionItems': 'Requiere Atención',
    'dashboard.allGood': 'Todos los artículos están en buenas condiciones',
    'dashboard.greatJob': '¡Excelente trabajo manteniendo tu inventario!',
    'dashboard.outOfStock': 'Sin Stock',
    
    // Scan View
    'scan.title': 'Escanear Artículos',
    'scan.subtitle': 'Escanea códigos de barras para actualizar rápidamente los artículos del inventario',
    'scan.manualEntry': 'Entrada Manual',
    'scan.cameraScan': 'Escaneo con Cámara',
    'scan.enterBarcode': 'Ingresar Código de Barras o ID',
    'scan.barcodePlaceholder': 'Escanea o escribe el código de barras aquí...',
    'scan.scannerActive': 'Escáner activo...',
    'scan.itemInformation': 'Información del Artículo',
    'scan.itemFound': 'Artículo Encontrado',
    'scan.name': 'Nombre',
    'scan.id': 'ID',
    'scan.condition': 'Condición',
    'scan.stock': 'Stock',
    'scan.available': 'Disponible',
    'scan.outOfStock': 'Sin Stock',
    'scan.selectConfiguration': 'Seleccionar Configuración',
    'scan.chooseConfiguration': 'Elige una configuración...',
    'scan.updating': 'Actualizando...',
    'scan.applyConfiguration': 'Aplicar Configuración',
    'scan.itemNotFound': 'Artículo No Encontrado',
    'scan.noItemFound': 'No se encontró ningún artículo con el código:',
    'scan.readyToScan': 'Listo para Escanear',
    'scan.scanToStart': 'Escanea o ingresa un código de barras para comenzar',
    'scan.clickToSearch': 'Hacer clic para buscar',
    'scan.scannerCooldown': 'Escáner en cooldown - esperando...',
    'scan.processingScan': 'Procesando escaneo...',
    'scan.scannerTips': 'Consejos para el escaneo:',
    'scan.tipStable': 'Mantén el código de barras estable y bien iluminado',
    'scan.tipProtection': 'El escáner tiene protección contra escaneos múltiples',
    'scan.tipCooldown': 'Espera 2 segundos entre escaneos del mismo código',
    
    // Configuration View
    'config.title': 'Configuraciones de Escaneo',
    'config.subtitle': 'Crear y gestionar actualizaciones automáticas de campos para el escaneo',
    'config.newConfiguration': 'Nueva Configuración',
    'config.editConfiguration': 'Editar Configuración',
    'config.createConfiguration': 'Crear Nueva Configuración',
    'config.save': 'Guardar',
    'config.cancel': 'Cancelar',
    'config.configName': 'Nombre de la Configuración',
    'config.configNamePlaceholder': 'ej., Verificación de Stock',
    'config.searchField': 'Campo de Búsqueda',
    'config.autoSave': 'Guardar automáticamente los cambios',
    'config.targetFields': 'Campos Objetivo',
    'config.fieldValue': 'Valor del Campo',
    'config.searchBy': 'Buscar por:',
    'config.targetFieldsCount': 'Campos Objetivo:',
    'config.moreFields': 'más',
    'config.autoSaveEnabled': 'Auto-guardado habilitado',
    'config.noConfigurations': 'Aún No Hay Configuraciones',
    'config.createFirst': 'Crea tu primera configuración de escaneo para comenzar',
    'config.createConfig': 'Crear Configuración',
    'config.nameRequired': 'El nombre de la configuración es requerido',
    'config.fieldRequired': 'Al menos un campo debe estar habilitado',
    'config.configUpdated': 'Configuración actualizada exitosamente',
    'config.configCreated': 'Configuración creada exitosamente',
    'config.confirmDelete': '¿Estás seguro de que quieres eliminar esta configuración?',
    'config.configDeleted': 'Configuración eliminada',
    'config.currentDate': 'Fecha Actual',
    'config.plus1Month': 'En 1 Mes',
    'config.plus3Months': 'En 3 Meses',
    'config.plus6Months': 'En 6 Meses',
    'config.plus1Year': 'En 1 Año',
    'config.customDate': 'Fecha Personalizada',
    'config.selectOption': 'Seleccionar opción...',
    'config.enterSelectValue': 'Ingresar valor de selección...',
    'config.enterMultipleValues': 'Ingresar valores separados por comas...',
    
    // History View
    'history.title': 'Historial de Escaneos',
    'history.subtitle': 'Rastrea todas las actividades de escaneo y cambios',
    'history.entries': 'entradas',
    'history.of': 'de',
    'history.filters': 'Filtros',
    'history.searchItems': 'Buscar Artículos',
    'history.searchPlaceholder': 'Buscar por nombre o ID del artículo...',
    'history.configuration': 'Configuración',
    'history.allConfigurations': 'Todas las Configuraciones',
    'history.date': 'Fecha',
    'history.noHistory': 'Aún No Hay Historial',
    'history.startScanning': 'Comienza a escanear artículos para ver actividad aquí',
    'history.noResults': 'No Se Encontraron Resultados',
    'history.adjustFilters': 'Intenta ajustar tus filtros de búsqueda',
    'history.clearFilters': 'Limpiar Filtros',
    'history.totalScans': 'Total de Escaneos',
    'history.configurationsUsed': 'Configuraciones Usadas',
    'history.uniqueItems': 'Artículos Únicos',
    'history.justNow': 'Ahora mismo',
    'history.minutesAgo': 'min atrás',
    'history.hoursAgo': 'h atrás',
    'history.daysAgo': 'd atrás',
    
    // Help tooltips
    'help.dashboard.overview': 'El panel de control muestra un resumen completo de tu inventario, incluyendo estadísticas clave y actividad reciente.',
    'help.dashboard.totalItems': 'Número total de artículos registrados en tu base de datos de inventario.',
    'help.dashboard.available': 'Cantidad de artículos que están marcados como disponibles en stock.',
    'help.dashboard.recentScans': 'Número total de escaneos realizados usando las configuraciones de escaneo.',
    'help.dashboard.needsAttention': 'Artículos que requieren atención, como aquellos en mal estado o sin stock.',
    'help.dashboard.recentActivity': 'Lista de los últimos escaneos realizados, mostrando qué artículos fueron procesados y cuándo.',
    'help.dashboard.needsAttentionItems': 'Artículos específicos que necesitan revisión debido a su condición o disponibilidad.',
    
    'help.scan.overview': 'La función de escaneo te permite buscar y actualizar artículos rápidamente usando códigos de barras o entrada manual.',
    'help.scan.manualEntry': 'Ingresa manualmente el código de barras o ID del artículo para buscarlo en la base de datos.',
    'help.scan.cameraScan': 'Usa la cámara de tu dispositivo para escanear códigos de barras automáticamente.',
    'help.scan.enterBarcode': 'Escribe o escanea el código de barras del artículo que quieres buscar.',
    'help.scan.itemInformation': 'Muestra los detalles del artículo encontrado, incluyendo nombre, ID, condición y disponibilidad.',
    'help.scan.selectConfiguration': 'Elige una configuración predefinida para aplicar cambios automáticos al artículo escaneado.',
    
    'help.config.overview': 'Las configuraciones de escaneo te permiten definir qué campos se actualizarán automáticamente cuando escanees un artículo.',
    'help.config.form': 'Formulario para crear o editar configuraciones de escaneo con campos personalizables.',
    'help.config.configName': 'Nombre descriptivo para identificar esta configuración (ej: "Verificación de Stock", "Control de Calidad").',
    'help.config.searchField': 'Campo de la base de datos que se usará para buscar artículos cuando escanees.',
    'help.config.autoSave': 'Si está habilitado, los cambios se guardarán automáticamente sin confirmación adicional.',
    'help.config.targetFields': 'Selecciona qué campos se actualizarán y define los valores que se aplicarán.',
    'help.config.fieldValue': 'Define el valor específico que se aplicará a este campo cuando se use esta configuración.',
    'help.config.configCard': 'Tarjeta de configuración que muestra el resumen y permite editar o eliminar la configuración.',
    
    'help.history.overview': 'El historial mantiene un registro completo de todas las actividades de escaneo realizadas.',
    'help.history.filters': 'Usa los filtros para buscar escaneos específicos por artículo, configuración o fecha.',
    'help.history.searchItems': 'Busca en el historial por nombre o ID de artículo.',
    'help.history.configuration': 'Filtra por la configuración específica que se usó para el escaneo.',
    'help.history.date': 'Filtra los escaneos por fecha específica.',
    'help.history.totalScans': 'Número total de escaneos registrados en el historial.',
    'help.history.configurationsUsed': 'Cantidad de configuraciones diferentes que se han utilizado.',
    'help.history.uniqueItems': 'Número de artículos únicos que han sido escaneados.',
    
    // Common
    'common.excellent': 'Excelente',
    'common.good': 'Bueno',
    'common.fair': 'Regular',
    'common.poor': 'Malo',
    'common.unknown': 'Desconocido',
    'common.active': 'Activo',
    'common.inactive': 'Inactivo',
    'common.maintenance': 'Mantenimiento',
    'common.checked': '✓ Marcado',
    'common.unchecked': '✗ Desmarcado',
    'common.currentDate': 'Fecha Actual',
    'common.customDate': 'Fecha Personalizada',
    'common.enterValue': 'Ingresar valor...',
    
    // Toast Messages
    'toast.demoActivated': '¡Modo demo activado! Explora todas las funcionalidades',
    'toast.notionConnected': '¡Conectado exitosamente a Notion!',
    'toast.connectionFailed': 'Falló la conexión a Notion. Por favor verifica tus credenciales.',
    'toast.connectionError': 'Error de conexión de red. Verifica tu conexión a internet, configuración de firewall, o extensiones del navegador que puedan estar bloqueando la solicitud.',
    'toast.disconnected': 'Desconectado de Notion',
    'toast.refreshFailed': 'Falló la actualización de la base de datos',
    'toast.itemFound': 'Artículo encontrado:',
    'toast.itemNotFound': 'Artículo no encontrado en la base de datos',
    'toast.scanError': 'Error procesando el escaneo',
    'toast.selectConfiguration': 'Por favor selecciona una configuración',
    'toast.configurationNotFound': 'Configuración no encontrada',
    'toast.itemUpdated': '¡Artículo actualizado exitosamente!',
    'toast.itemUpdateFailed': 'Falló la actualización del artículo',
    'toast.configurationError': 'Error aplicando la configuración',
    'toast.itemUpdatedDemo': 'Artículo actualizado exitosamente (Modo Demo)',
  },
  'en-US': {
    // Header
    'header.title': 'Notinvent',
    'header.dashboard': 'Dashboard',
    'header.scan': 'Scan',
    'header.configuration': 'Configuration',
    'header.history': 'History',
    'header.connected': 'Connected',
    'header.disconnected': 'Disconnected',
    'header.demoMode': 'Demo Mode',
    'header.disconnect': 'Disconnect',
    'header.exitDemo': 'Exit demo mode',
    
    // Theme
    'theme.light': 'Light Mode',
    'theme.dark': 'Dark Mode',
    'theme.system': 'Follow System',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.logout': 'Logout',
    'auth.userSettings': 'User Settings',
    'auth.confirmLogout': 'Are you sure you want to logout?',
    'auth.welcome': 'Welcome',
    'auth.welcomeBack': 'Welcome back',
    'auth.accountCreated': 'Account created successfully',
    'auth.loginSuccess': 'Login successful',
    'auth.logoutSuccess': 'Logout successful',
    'auth.invalidCredentials': 'Invalid credentials',
    'auth.emailRequired': 'Email is required',
    'auth.passwordRequired': 'Password is required',
    'auth.nameRequired': 'Name is required',
    'auth.emailInvalid': 'Please enter a valid email',
    'auth.passwordTooShort': 'Password must be at least 8 characters',
    'auth.passwordsNotMatch': 'Passwords do not match',
    'auth.emailExists': 'This email is already registered',
    'auth.userNotFound': 'User not found',
    'auth.networkError': 'Network error. Check your internet connection.',
    
    // Connection View
    'connection.title': 'Connect to Notion',
    'connection.subtitle': 'Enter your Notion integration credentials to get started',
    'connection.demoButton': 'Explore in Demo Mode',
    'connection.demoSubtitle': 'Try all features without configuration',
    'connection.orConnect': 'or connect your Notion',
    'connection.token': 'Integration Token',
    'connection.tokenPlaceholder': 'secret_...',
    'connection.tokenRequired': 'Integration token is required',
    'connection.databaseId': 'Database ID',
    'connection.databaseIdPlaceholder': 'Database ID from Notion URL',
    'connection.databaseIdRequired': 'Database ID is required',
    'connection.workspaceName': 'Workspace Name (Optional)',
    'connection.workspaceNamePlaceholder': 'My Company Workspace',
    'connection.connecting': 'Connecting...',
    'connection.connect': 'Connect to Notion',
    'connection.setupInstructions': 'Setup Instructions:',
    'connection.step1': 'Create a Notion integration at notion.so/my-integrations',
    'connection.step2': 'Copy the integration token',
    'connection.step3': 'Share your database with the integration',
    'connection.step4': 'Copy the database ID from the URL',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your inventory management system',
    'dashboard.refresh': 'Refresh',
    'dashboard.totalItems': 'Total Items',
    'dashboard.available': 'Available',
    'dashboard.recentScans': 'Recent Scans',
    'dashboard.needsAttention': 'Need Attention',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.noActivity': 'No recent activity',
    'dashboard.startScanning': 'Start scanning to see activity here',
    'dashboard.scannedWith': 'Scanned with',
    'dashboard.needsAttentionItems': 'Needs Attention',
    'dashboard.allGood': 'All items are in good condition',
    'dashboard.greatJob': 'Great job maintaining your inventory!',
    'dashboard.outOfStock': 'Out of Stock',
    
    // Scan View
    'scan.title': 'Scan Items',
    'scan.subtitle': 'Scan barcodes to quickly update inventory items',
    'scan.manualEntry': 'Manual Entry',
    'scan.cameraScan': 'Camera Scan',
    'scan.enterBarcode': 'Enter Barcode or ID',
    'scan.barcodePlaceholder': 'Scan or type barcode here...',
    'scan.scannerActive': 'Scanner active...',
    'scan.itemInformation': 'Item Information',
    'scan.itemFound': 'Item Found',
    'scan.name': 'Name',
    'scan.id': 'ID',
    'scan.condition': 'Condition',
    'scan.stock': 'Stock',
    'scan.available': 'Available',
    'scan.outOfStock': 'Out of Stock',
    'scan.selectConfiguration': 'Select Configuration',
    'scan.chooseConfiguration': 'Choose a configuration...',
    'scan.updating': 'Updating...',
    'scan.applyConfiguration': 'Apply Configuration',
    'scan.itemNotFound': 'Item Not Found',
    'scan.noItemFound': 'No item found with code:',
    'scan.readyToScan': 'Ready to Scan',
    'scan.scanToStart': 'Scan or enter a barcode to get started',
    'scan.clickToSearch': 'Click to search',
    'scan.scannerCooldown': 'Scanner in cooldown - waiting...',
    'scan.processingScan': 'Processing scan...',
    'scan.scannerTips': 'Scanning tips:',
    'scan.tipStable': 'Keep the barcode stable and well-lit',
    'scan.tipProtection': 'Scanner has protection against multiple scans',
    'scan.tipCooldown': 'Wait 2 seconds between scans of the same code',
    
    // Configuration View
    'config.title': 'Scan Configurations',
    'config.subtitle': 'Create and manage automatic field updates for scanning',
    'config.newConfiguration': 'New Configuration',
    'config.editConfiguration': 'Edit Configuration',
    'config.createConfiguration': 'Create New Configuration',
    'config.save': 'Save',
    'config.cancel': 'Cancel',
    'config.configName': 'Configuration Name',
    'config.configNamePlaceholder': 'e.g., Stock Check',
    'config.searchField': 'Search Field',
    'config.autoSave': 'Auto-save changes',
    'config.targetFields': 'Target Fields',
    'config.fieldValue': 'Field Value',
    'config.searchBy': 'Search by:',
    'config.targetFieldsCount': 'Target Fields:',
    'config.moreFields': 'more',
    'config.autoSaveEnabled': 'Auto-save enabled',
    'config.noConfigurations': 'No Configurations Yet',
    'config.createFirst': 'Create your first scan configuration to get started',
    'config.createConfig': 'Create Configuration',
    'config.nameRequired': 'Configuration name is required',
    'config.fieldRequired': 'At least one field must be enabled',
    'config.configUpdated': 'Configuration updated successfully',
    'config.configCreated': 'Configuration created successfully',
    'config.confirmDelete': 'Are you sure you want to delete this configuration?',
    'config.configDeleted': 'Configuration deleted',
    'config.currentDate': 'Current Date',
    'config.plus1Month': 'In 1 Month',
    'config.plus3Months': 'In 3 Months',
    'config.plus6Months': 'In 6 Months',
    'config.plus1Year': 'In 1 Year',
    'config.customDate': 'Custom Date',
    'config.selectOption': 'Select option...',
    'config.enterSelectValue': 'Enter select value...',
    'config.enterMultipleValues': 'Enter comma-separated values...',
    
    // History View
    'history.title': 'Scan History',
    'history.subtitle': 'Track all scanning activities and changes',
    'history.entries': 'entries',
    'history.of': 'of',
    'history.filters': 'Filters',
    'history.searchItems': 'Search Items',
    'history.searchPlaceholder': 'Search by item name or ID...',
    'history.configuration': 'Configuration',
    'history.allConfigurations': 'All Configurations',
    'history.date': 'Date',
    'history.noHistory': 'No History Yet',
    'history.startScanning': 'Start scanning items to see activity here',
    'history.noResults': 'No Results Found',
    'history.adjustFilters': 'Try adjusting your search filters',
    'history.clearFilters': 'Clear Filters',
    'history.totalScans': 'Total Scans',
    'history.configurationsUsed': 'Configurations Used',
    'history.uniqueItems': 'Unique Items',
    'history.justNow': 'Just now',
    'history.minutesAgo': 'min ago',
    'history.hoursAgo': 'h ago',
    'history.daysAgo': 'd ago',
    
    // Help tooltips
    'help.dashboard.overview': 'The dashboard provides a comprehensive overview of your inventory, including key statistics and recent activity.',
    'help.dashboard.totalItems': 'Total number of items registered in your inventory database.',
    'help.dashboard.available': 'Number of items that are marked as available in stock.',
    'help.dashboard.recentScans': 'Total number of scans performed using scan configurations.',
    'help.dashboard.needsAttention': 'Items that require attention, such as those in poor condition or out of stock.',
    'help.dashboard.recentActivity': 'List of the most recent scans performed, showing which items were processed and when.',
    'help.dashboard.needsAttentionItems': 'Specific items that need review due to their condition or availability.',
    
    'help.scan.overview': 'The scan function allows you to quickly search and update items using barcodes or manual entry.',
    'help.scan.manualEntry': 'Manually enter the barcode or ID of the item to search for it in the database.',
    'help.scan.cameraScan': 'Use your device\'s camera to automatically scan barcodes.',
    'help.scan.enterBarcode': 'Type or scan the barcode of the item you want to search for.',
    'help.scan.itemInformation': 'Shows the details of the found item, including name, ID, condition, and availability.',
    'help.scan.selectConfiguration': 'Choose a predefined configuration to apply automatic changes to the scanned item.',
    
    'help.config.overview': 'Scan configurations allow you to define which fields will be automatically updated when you scan an item.',
    'help.config.form': 'Form to create or edit scan configurations with customizable fields.',
    'help.config.configName': 'Descriptive name to identify this configuration (e.g., "Stock Check", "Quality Control").',
    'help.config.searchField': 'Database field that will be used to search for items when scanning.',
    'help.config.autoSave': 'If enabled, changes will be saved automatically without additional confirmation.',
    'help.config.targetFields': 'Select which fields will be updated and define the values to be applied.',
    'help.config.fieldValue': 'Define the specific value that will be applied to this field when using this configuration.',
    'help.config.configCard': 'Configuration card showing summary and allowing editing or deletion of the configuration.',
    
    'help.history.overview': 'The history maintains a complete record of all scanning activities performed.',
    'help.history.filters': 'Use filters to search for specific scans by item, configuration, or date.',
    'help.history.searchItems': 'Search the history by item name or ID.',
    'help.history.configuration': 'Filter by the specific configuration that was used for the scan.',
    'help.history.date': 'Filter scans by specific date.',
    'help.history.totalScans': 'Total number of scans recorded in the history.',
    'help.history.configurationsUsed': 'Number of different configurations that have been used.',
    'help.history.uniqueItems': 'Number of unique items that have been scanned.',
    
    // Common
    'common.excellent': 'Excellent',
    'common.good': 'Good',
    'common.fair': 'Fair',
    'common.poor': 'Poor',
    'common.unknown': 'Unknown',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.maintenance': 'Maintenance',
    'common.checked': '✓ Checked',
    'common.unchecked': '✗ Unchecked',
    'common.currentDate': 'Current Date',
    'common.customDate': 'Custom Date',
    'common.enterValue': 'Enter value...',
    
    // Toast Messages
    'toast.demoActivated': 'Demo mode activated! Explore all features',
    'toast.notionConnected': 'Successfully connected to Notion!',
    'toast.connectionFailed': 'Failed to connect to Notion. Please check your credentials.',
    'toast.connectionError': 'Network connection error. Please check your internet connection, firewall settings, or browser extensions that may be blocking the request.',
    'toast.disconnected': 'Disconnected from Notion',
    'toast.refreshFailed': 'Failed to refresh database',
    'toast.itemFound': 'Item found:',
    'toast.itemNotFound': 'Item not found in database',
    'toast.scanError': 'Error processing scan',
    'toast.selectConfiguration': 'Please select a configuration',
    'toast.configurationNotFound': 'Configuration not found',
    'toast.itemUpdated': 'Item updated successfully!',
    'toast.itemUpdateFailed': 'Failed to update item',
    'toast.configurationError': 'Error applying configuration',
    'toast.itemUpdatedDemo': 'Item updated successfully (Demo Mode)',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('es-MX');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('app-language') as Language;
    if (savedLanguage && (savedLanguage === 'es-MX' || savedLanguage === 'en-US')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};